### ISSUE TITLE
Not working inside HomeAssistant node red Addon

### ISSUE THREAD

**Issue by sheminasalam** [w35l3y/node-red-contrib-localtunnel#1]
Hi there, I appreciate the great work but I am having some issues. I tried this node with the node red home addon which is installed as a docker container. but even when it connected to the localtunnel server and gave me an url, it failed to expose any port. When I tried the url provided, I got 404 error. I have been running localtunnel outside node red in the conventional manner and it works as intended.

**Comment by w35l3y** [comment]
Interesting.
How did you install home assistant? I use HAOS.
I haven't tested any other ways of using home assistant.

Now I am using [cloudflared tunneling](https://github.com/w35l3y/hassio-addons/tree/main/cloudflare_tunnel). So I don't know whether recent HA versions modified something that made it stop working.

I would need more details about the problem to understand exactly what happened.

**Comment by sheminasalam** [comment]
I am running supervised HA installation in RPi 4. Actually when I deploy this node, my nodered crashes. I can see the following error in nodered addon log.
```
31 Oct 16:52:57 - [info] [localtunnel:aa6d5f73ee93d8f8] Connected: https://rude-squid-73.loca.lt
31 Oct 16:52:58 - [red] Uncaught Exception:
31 Oct 16:52:58 - TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string or an instance of Buffer or URL. Received undefined
    at Object.openSync (fs.js:490:10)
    at Object.readFileSync (fs.js:394:35)
    at getLocalCertOpts (/config/node-red/node_modules/localtunnel/lib/TunnelCluster.js:79:24)
    at connLocal (/config/node-red/node_modules/localtunnel/lib/TunnelCluster.js:86:62)
    at Socket.<anonymous> (/config/node-red/node_modules/localtunnel/lib/TunnelCluster.js:149:7)
    at Object.onceWrapper (events.js:519:28)
    at Socket.emit (events.js:412:35)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1134:10)
```
After this nodered restarts

I tried to install the cloudflare addon also but it is giving me the following error.
```
The command '/bin/ash -o pipefail -c CVERSION="latest/download" ARCH="${BUILD_ARCH}" && if [[ "${BUILD_ARCH}" = "aarch64" ]]; then ARCH="arm64"; fi && if [[ "${BUILD_ARCH}" = "amd64" ]]; then ARCH="amd64"; fi && if [[ "${BUILD_ARCH}" = "armhf" ]]; then ARCH="arm"; fi && if [[ "${BUILD_ARCH}" = "armv7" ]]; then ARCH="arm"; fi && if [[ "${BUILD_ARCH}" = "i386" ]]; then ARCH="386"; fi && apk add --no-cache libc6-compat yq && wget -O /usr/local/bin/cloudflared https://github.com/cloudflare/cloudflared/releases/$CVERSION/cloudflared-linux-$ARCH && chmod +x /usr/local/bin/cloudflared' returned a non-zero code: 2
```

**Comment by w35l3y** [comment]
`The "path" argument must be of type string or an instance of Buffer or URL. Received undefined.`

It seems "path" parameter was not filled.
If you are not using SSL, consider unchecking "HTTPS"

`I tried to install the cloudflare addon also but it is giving me the following error.`
I also haven't tested it with other installations, other than HAOS. Have you followed the instructions?

**Comment by sheminasalam** [comment]
Thanks bro..it worked.
Appreciate the good work.
Hope you can also sort out the Cloudlfare tunnel issue
